import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, HandHeart, Scale, Sprout, Users } from "lucide-react";
import { PageHero } from "@/components/PageHero";
import { programs } from "@/lib/content";

export const metadata:Metadata={title:"About us",description:"Meet the people and purpose behind Caring Hearts Global Relief and Development."};

export default function AboutPage(){const values=[{title:"Compassion",copy:"We see the person before the need and lead with empathy.",icon:HandHeart},{title:"Integrity",copy:"We act transparently and steward every gift with care.",icon:Scale},{title:"Empowerment",copy:"We listen first and strengthen local knowledge and leadership.",icon:Users},{title:"Sustainability",copy:"We pursue practical solutions designed to last.",icon:Sprout}];return <>
 <PageHero eyebrow="Who are we?" title="Human dignity is where every solution begins." description="Caring Hearts Global Relief and Development is a humanitarian nonprofit dedicated to uplifting children and families across Africa—particularly in the most underserved regions of West Africa." action/>
 <section className="py-20 lg:py-28"><div className="container-shell grid items-center gap-14 lg:grid-cols-2"><div><p className="eyebrow text-[#c76542]">Our story</p><h2 className="display-title mt-4 text-5xl font-semibold sm:text-6xl">Turning struggle into strength, together.</h2><div className="mt-7 space-y-5 text-lg leading-8 text-[#18342d]/72"><p>Founded on the principles of compassion, service, and empowerment, we exist to turn struggle into strength through direct relief and long-term development.</p><p>We provide essential aid—such as food, clean water, and basic healthcare—while investing in sustainable community-driven solutions to fight poverty and hunger at their roots. Our work is guided by integrity, collaboration, and a deep belief that every child deserves the opportunity to thrive.</p><p>As a grassroots organization, we work hand-in-hand with local communities, dedicated volunteers, and generous donors to build a future where dignity and hope replace hardship and despair.</p><p>Together, we are compassion in action—and every effort brings us closer to lasting change.</p></div></div><div className="relative aspect-[4/5] overflow-hidden rounded-[2rem]"><Image src="/images/community-collage.webp" alt="Hands holding a heart-shaped stone" fill className="object-cover" sizes="(max-width:1024px) 100vw,50vw"/></div></div></section>
 <section className="bg-[#fff9d1] py-20 lg:py-24"><div className="container-shell"><p className="eyebrow">What we do</p><h2 className="section-title mt-4 max-w-3xl">Urgent support with long-term purpose.</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-black/65">We focus on impactful programs that meet the urgent needs of vulnerable communities while fostering long-term self-sufficiency. Our key programs include:</p><div className="mt-10 grid gap-4 md:grid-cols-2">{programs.map(({title,description,icon:Icon})=><article key={title} className="flex gap-4 rounded-3xl bg-white p-6"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#48d6d2]"><Icon size={21}/></span><div><h3 className="text-xl">{title}</h3><p className="mt-2 leading-6 text-black/62">{description}</p></div></article>)}</div></div></section>
 <section className="bg-[#f7f3e9] py-20"><div className="container-shell"><div className="max-w-2xl"><p className="eyebrow text-[#c76542]">What guides us</p><h2 className="display-title mt-4 text-5xl font-semibold">Values made visible through action.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{values.map(({title,copy,icon:Icon})=><article key={title} className="rounded-3xl bg-white p-7"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#dce8df] text-[#236958]"><Icon/></span><h3 className="mt-6 text-2xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#18342d]/65">{copy}</p></article>)}</div><div className="mt-12 text-center"><Link href="/our-mission-vision" className="button-ghost">Our mission & vision <ArrowRight size={17}/></Link></div></div></section>
</>}
