"use client";
import { ArrowRight, Check, LockKeyhole } from "lucide-react";
import { useState } from "react";

const donateUrl="https://pomegranate-reed-abws.squarespace.com/giving-page-1-1";
export function DonationExperience(){const [amount,setAmount]=useState(40);const [monthly,setMonthly]=useState(true);return <section className="bg-[#f7f3e9] py-16 lg:py-24"><div className="container-shell grid gap-10 lg:grid-cols-[1fr_.82fr]">
 <div><p className="eyebrow text-[#c76542]">Your generosity in motion</p><h2 className="display-title mt-4 max-w-2xl text-5xl font-semibold sm:text-6xl">A gift today can change a family’s tomorrow.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-[#18342d]/70">Together, we can turn struggle into strength and despair into hope. Every gift helps nourish children, support vulnerable families, and create lasting change in West African communities.</p><div className="mt-9 grid gap-3 sm:grid-cols-2">{["Provide immediate nourishment","Strengthen education and health","Support urgent crisis response","Build paths to self-reliance"].map(x=><p key={x} className="flex gap-3 font-bold"><Check className="mt-0.5 shrink-0 text-[#c76542]" size={20}/>{x}</p>)}</div><div className="mt-10 rounded-3xl bg-[#153f35] p-7 text-white"><p className="font-[family-name:var(--font-display)] text-3xl font-semibold">Your donation is tax-deductible.</p><p className="mt-2 text-sm leading-6 text-white/68">Caring Hearts Global Relief & Development is a registered 501(c)(3) nonprofit organization. Tax ID #99-3733743.</p></div></div>
 <div className="h-fit rounded-[2rem] bg-white p-6 shadow-[0_25px_70px_rgba(24,52,45,.12)] sm:p-8"><p className="eyebrow text-[#236958]">Choose your gift</p><div className="mt-5 grid grid-cols-4 gap-2">{[20,40,75,100].map(x=><button key={x} onClick={()=>setAmount(x)} className={`rounded-xl border py-3 font-extrabold ${amount===x?"border-[#c76542] bg-[#c76542] text-white":"border-[#153f35]/15 hover:border-[#c76542]"}`}>${x}</button>)}</div><label className="mt-4 block text-xs font-extrabold tracking-wider text-[#18342d]/55 uppercase">Custom amount</label><div className="mt-2 flex items-center rounded-xl border border-[#153f35]/15 px-4"><span className="font-bold">$</span><input type="number" min="1" value={amount} onChange={e=>setAmount(Number(e.target.value))} className="w-full bg-transparent px-2 py-4 font-bold outline-none" aria-label="Donation amount"/></div><div className="mt-5 grid grid-cols-2 rounded-xl bg-[#f7f3e9] p-1"><button onClick={()=>setMonthly(false)} className={`rounded-lg py-3 text-sm font-extrabold ${!monthly?"bg-white shadow":""}`}>One time</button><button onClick={()=>setMonthly(true)} className={`rounded-lg py-3 text-sm font-extrabold ${monthly?"bg-white shadow":""}`}>Monthly</button></div><div className="my-6 border-t border-[#153f35]/10"/><div className="flex items-end justify-between"><span className="text-sm text-[#18342d]/60">Your {monthly?"monthly":"one-time"} gift</span><span className="font-[family-name:var(--font-display)] text-4xl font-bold">${amount||0}</span></div><a href={donateUrl} target="_blank" rel="noreferrer" className="button-primary mt-6 w-full">Continue to secure donation <ArrowRight size={18}/></a><p className="mt-4 flex items-center justify-center gap-2 text-center text-xs text-[#18342d]/50"><LockKeyhole size={14}/>Secure donation processing opens in a new tab.</p></div>
 </div></section>}
