import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Mail } from "lucide-react";
import { CookiePreferencesButton } from "@/components/CookieConsent";
export function Footer(){return <footer className="bg-[#222] text-white"><div className="container-shell py-16 lg:py-20">
 <div className="mb-14 grid items-end gap-6 rounded-[30px] bg-[#daf7f6] p-7 text-black sm:p-10 lg:grid-cols-[1fr_auto]"><div><p className="eyebrow">Subscribe</p><h2 className="mt-3 text-3xl sm:text-4xl">Stay close to the work.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-black/65">Be the first to hear about new projects, inspiring stories, and volunteer opportunities. Subscribe to our newsletter to stay informed and engaged with the impact we’re making together. We respect your privacy.</p></div><a href="mailto:contact@caringheartsglobal.org?subject=Newsletter%20subscription" className="button-ghost">Subscribe by email <ArrowRight size={17}/></a></div>
 <div className="grid gap-12 border-b border-white/15 pb-14 lg:grid-cols-[1.3fr_.7fr_.7fr_.8fr]">
  <div><div className="flex items-center gap-3"><Image src="/images/brand-mark.webp" alt="" width={58} height={58}/><p className="text-xl font-semibold leading-none">Caring Hearts<br/>Global</p></div><p className="mt-6 max-w-sm text-sm leading-6 text-white/65">Compassionate relief and community-led development for children and families across Africa.</p><Link href="/giving-page-1-1" className="button-primary mt-7">Make a difference <ArrowRight size={17}/></Link></div>
  <div><p className="mb-5 text-xs font-bold uppercase text-white/40">Explore</p><div className="grid gap-3 text-sm"><Link href="/about">About us</Link><Link href="/our-mission-vision">Mission & vision</Link><Link href="/our-team">Our team</Link><Link href="/programs">Programs</Link><Link href="/contact">Contact</Link></div></div>
  <div><p className="mb-5 text-xs font-bold uppercase text-white/40">Our work</p><div className="grid gap-3 text-sm"><Link href="/programs">Food Programs</Link><Link href="/programs">Water Programs</Link><Link href="/programs">Education Programs</Link><Link href="/programs">Emergency Aid</Link><Link href="/programs">Health Support</Link><Link href="/programs">Self-Reliance</Link><Link href="/programs">Solar Energy</Link><Link href="/programs">Zakat</Link></div></div>
  <div><p className="mb-5 text-xs font-bold uppercase text-white/40">Contact</p><a href="mailto:contact@caringheartsglobal.org" className="flex items-center gap-2 text-sm"><Mail size={16}/>contact@caringheartsglobal.org</a><p className="mt-4 text-sm text-white/65">Baton Rouge, Louisiana<br/>+1 (225) 384-0471</p></div>
 </div><div className="flex flex-col gap-3 pt-6 text-xs text-white/45 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} Caring Hearts Global Relief & Development Limited · All Rights Reserved</p><div className="flex flex-wrap gap-x-5 gap-y-2"><p>501(c)(3) nonprofit · Tax ID #99-3733743</p><Link href="/cookie-policy" className="hover:text-white">Cookie Policy</Link><CookiePreferencesButton/></div></div>
 </div></footer>}
